version: '3'
services:
 selenoid:
   network_mode: bridge
   image: aerokube/selenoid
   volumes:
     - "./:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./video:/opt/selenoid/video"
        #  - "/C/Users/Dell/Documents/video:/opt/selenoid/video"
   environment:
    #  - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Users/Dell/Documents/video
     - OVERRIDE_VIDEO_OUTPUT_DIR=./video
     - TZ=Europe/Amsterdam
   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
   ports:
     - "4444:4444"

 selenoid-ui:
   image: "aerokube/selenoid-ui"
   network_mode: bridge
   links:
     - selenoid
   ports:
     - "8080:8080"
   command: ["--selenoid-uri", "http://selenoid:4444"]